/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.alma.enumeration.ui.internal.EnumerationActivator;

public class EnumerationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EnumerationActivator.getInstance().getInjector("org.xtext.alma.enumeration.Enumeration");
	}

}
