/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.ui.contentassist;

import org.xtext.alma.enumeration.ui.contentassist.AbstractEnumerationProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EnumerationProposalProvider extends AbstractEnumerationProposalProvider {
}
