/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EnumerationAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/alma/enumeration/parser/antlr/internal/InternalEnumeration.tokens");
	}
}
