/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.alma.enumeration.parser.antlr.internal.InternalEnumerationParser;
import org.xtext.alma.enumeration.services.EnumerationGrammarAccess;

public class EnumerationParser extends AbstractAntlrParser {

	@Inject
	private EnumerationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEnumerationParser createParser(XtextTokenStream stream) {
		return new InternalEnumerationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EnumType";
	}

	public EnumerationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EnumerationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
