/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.alma.sdmdsl.sdmdsl.Addition;
import org.xtext.alma.sdmdsl.sdmdsl.Defined;
import org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Defined</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.impl.DefinedImpl#getDataDimValue <em>Data Dim Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefinedImpl extends DimensionsImpl implements Defined
{
  /**
   * The cached value of the '{@link #getDataDimValue() <em>Data Dim Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataDimValue()
   * @generated
   * @ordered
   */
  protected Addition dataDimValue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefinedImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SdmdslPackage.Literals.DEFINED;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Addition getDataDimValue()
  {
    return dataDimValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDataDimValue(Addition newDataDimValue, NotificationChain msgs)
  {
    Addition oldDataDimValue = dataDimValue;
    dataDimValue = newDataDimValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SdmdslPackage.DEFINED__DATA_DIM_VALUE, oldDataDimValue, newDataDimValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDataDimValue(Addition newDataDimValue)
  {
    if (newDataDimValue != dataDimValue)
    {
      NotificationChain msgs = null;
      if (dataDimValue != null)
        msgs = ((InternalEObject)dataDimValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SdmdslPackage.DEFINED__DATA_DIM_VALUE, null, msgs);
      if (newDataDimValue != null)
        msgs = ((InternalEObject)newDataDimValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SdmdslPackage.DEFINED__DATA_DIM_VALUE, null, msgs);
      msgs = basicSetDataDimValue(newDataDimValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SdmdslPackage.DEFINED__DATA_DIM_VALUE, newDataDimValue, newDataDimValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SdmdslPackage.DEFINED__DATA_DIM_VALUE:
        return basicSetDataDimValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SdmdslPackage.DEFINED__DATA_DIM_VALUE:
        return getDataDimValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SdmdslPackage.DEFINED__DATA_DIM_VALUE:
        setDataDimValue((Addition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SdmdslPackage.DEFINED__DATA_DIM_VALUE:
        setDataDimValue((Addition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SdmdslPackage.DEFINED__DATA_DIM_VALUE:
        return dataDimValue != null;
    }
    return super.eIsSet(featureID);
  }

} //DefinedImpl
