/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration;

import org.xtext.alma.enumeration.AbstractEnumerationRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EnumerationRuntimeModule extends AbstractEnumerationRuntimeModule {
}
