/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration;

import org.xtext.alma.enumeration.EnumerationStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EnumerationStandaloneSetup extends EnumerationStandaloneSetupGenerated {
  public static void doSetup() {
    EnumerationStandaloneSetup _enumerationStandaloneSetup = new EnumerationStandaloneSetup();
    _enumerationStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
