/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.sdmdsl;

import org.xtext.alma.sdmdsl.AbstractSdmdslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SdmdslRuntimeModule extends AbstractSdmdslRuntimeModule {
}
