/*
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.sdmdsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class SdmdslUiModule extends AbstractSdmdslUiModule {
}
