/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.container;

import org.xtext.alma.container.ContainerStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ContainerStandaloneSetup extends ContainerStandaloneSetupGenerated {
  public static void doSetup() {
    ContainerStandaloneSetup _containerStandaloneSetup = new ContainerStandaloneSetup();
    _containerStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
