/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.container;

import org.xtext.alma.container.AbstractContainerRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ContainerRuntimeModule extends AbstractContainerRuntimeModule {
}
