/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.enumeration;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.alma.enumeration.enumeration.EnumerationFactory
 * @model kind="package"
 * @generated
 */
public interface EnumerationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "enumeration";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/alma/enumeration/Enumeration";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "enumeration";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EnumerationPackage eINSTANCE = org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.alma.enumeration.enumeration.impl.EnumTypeImpl <em>Enum Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.alma.enumeration.enumeration.impl.EnumTypeImpl
   * @see org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl#getEnumType()
   * @generated
   */
  int ENUM_TYPE = 0;

  /**
   * The feature id for the '<em><b>Doc Global</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__DOC_GLOBAL = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__VERSION = 1;

  /**
   * The feature id for the '<em><b>Revision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__REVISION = 2;

  /**
   * The feature id for the '<em><b>Xmlns</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__XMLNS = 3;

  /**
   * The feature id for the '<em><b>Doc Enum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__DOC_ENUM = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__NAME = 5;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE__VALUES = 6;

  /**
   * The number of structural features of the '<em>Enum Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_TYPE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.alma.enumeration.enumeration.impl.EnumValueWithoutCommaImpl <em>Enum Value Without Comma</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.alma.enumeration.enumeration.impl.EnumValueWithoutCommaImpl
   * @see org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl#getEnumValueWithoutComma()
   * @generated
   */
  int ENUM_VALUE_WITHOUT_COMMA = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_WITHOUT_COMMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_WITHOUT_COMMA__DOC = 1;

  /**
   * The number of structural features of the '<em>Enum Value Without Comma</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_WITHOUT_COMMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.alma.enumeration.enumeration.impl.EnumValueImpl <em>Enum Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.alma.enumeration.enumeration.impl.EnumValueImpl
   * @see org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl#getEnumValue()
   * @generated
   */
  int ENUM_VALUE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE__NAME = 0;

  /**
   * The feature id for the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE__DOC = 1;

  /**
   * The number of structural features of the '<em>Enum Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.alma.enumeration.enumeration.EnumType <em>Enum Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Type</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType
   * @generated
   */
  EClass getEnumType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumType#getDocGlobal <em>Doc Global</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doc Global</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getDocGlobal()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_DocGlobal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumType#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getVersion()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_Version();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumType#getRevision <em>Revision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Revision</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getRevision()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_Revision();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumType#getXmlns <em>Xmlns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xmlns</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getXmlns()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_Xmlns();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumType#getDocEnum <em>Doc Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doc Enum</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getDocEnum()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_DocEnum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getName()
   * @see #getEnumType()
   * @generated
   */
  EAttribute getEnumType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.alma.enumeration.enumeration.EnumType#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumType#getValues()
   * @see #getEnumType()
   * @generated
   */
  EReference getEnumType_Values();

  /**
   * Returns the meta object for class '{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma <em>Enum Value Without Comma</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Value Without Comma</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma
   * @generated
   */
  EClass getEnumValueWithoutComma();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getName()
   * @see #getEnumValueWithoutComma()
   * @generated
   */
  EAttribute getEnumValueWithoutComma_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getDoc <em>Doc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doc</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getDoc()
   * @see #getEnumValueWithoutComma()
   * @generated
   */
  EAttribute getEnumValueWithoutComma_Doc();

  /**
   * Returns the meta object for class '{@link org.xtext.alma.enumeration.enumeration.EnumValue <em>Enum Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Value</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumValue
   * @generated
   */
  EClass getEnumValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumValue#getName()
   * @see #getEnumValue()
   * @generated
   */
  EAttribute getEnumValue_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.alma.enumeration.enumeration.EnumValue#getDoc <em>Doc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doc</em>'.
   * @see org.xtext.alma.enumeration.enumeration.EnumValue#getDoc()
   * @see #getEnumValue()
   * @generated
   */
  EAttribute getEnumValue_Doc();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EnumerationFactory getEnumerationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.alma.enumeration.enumeration.impl.EnumTypeImpl <em>Enum Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.alma.enumeration.enumeration.impl.EnumTypeImpl
     * @see org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl#getEnumType()
     * @generated
     */
    EClass ENUM_TYPE = eINSTANCE.getEnumType();

    /**
     * The meta object literal for the '<em><b>Doc Global</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__DOC_GLOBAL = eINSTANCE.getEnumType_DocGlobal();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__VERSION = eINSTANCE.getEnumType_Version();

    /**
     * The meta object literal for the '<em><b>Revision</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__REVISION = eINSTANCE.getEnumType_Revision();

    /**
     * The meta object literal for the '<em><b>Xmlns</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__XMLNS = eINSTANCE.getEnumType_Xmlns();

    /**
     * The meta object literal for the '<em><b>Doc Enum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__DOC_ENUM = eINSTANCE.getEnumType_DocEnum();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_TYPE__NAME = eINSTANCE.getEnumType_Name();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_TYPE__VALUES = eINSTANCE.getEnumType_Values();

    /**
     * The meta object literal for the '{@link org.xtext.alma.enumeration.enumeration.impl.EnumValueWithoutCommaImpl <em>Enum Value Without Comma</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.alma.enumeration.enumeration.impl.EnumValueWithoutCommaImpl
     * @see org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl#getEnumValueWithoutComma()
     * @generated
     */
    EClass ENUM_VALUE_WITHOUT_COMMA = eINSTANCE.getEnumValueWithoutComma();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_VALUE_WITHOUT_COMMA__NAME = eINSTANCE.getEnumValueWithoutComma_Name();

    /**
     * The meta object literal for the '<em><b>Doc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_VALUE_WITHOUT_COMMA__DOC = eINSTANCE.getEnumValueWithoutComma_Doc();

    /**
     * The meta object literal for the '{@link org.xtext.alma.enumeration.enumeration.impl.EnumValueImpl <em>Enum Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.alma.enumeration.enumeration.impl.EnumValueImpl
     * @see org.xtext.alma.enumeration.enumeration.impl.EnumerationPackageImpl#getEnumValue()
     * @generated
     */
    EClass ENUM_VALUE = eINSTANCE.getEnumValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_VALUE__NAME = eINSTANCE.getEnumValue_Name();

    /**
     * The meta object literal for the '<em><b>Doc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_VALUE__DOC = eINSTANCE.getEnumValue_Doc();

  }

} //EnumerationPackage
