/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.enumeration;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Value Without Comma</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getDoc <em>Doc</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.enumeration.enumeration.EnumerationPackage#getEnumValueWithoutComma()
 * @model
 * @generated
 */
public interface EnumValueWithoutComma extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.alma.enumeration.enumeration.EnumerationPackage#getEnumValueWithoutComma_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doc</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see org.xtext.alma.enumeration.enumeration.EnumerationPackage#getEnumValueWithoutComma_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link org.xtext.alma.enumeration.enumeration.EnumValueWithoutComma#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

} // EnumValueWithoutComma
