/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.alma.sdmdsl.ui.internal.SdmdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SdmdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SdmdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SdmdslActivator.getInstance().getInjector(SdmdslActivator.ORG_XTEXT_ALMA_SDMDSL_SDMDSL);
	}
	
}
