/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.sdmdsl.scoping;

import org.xtext.alma.sdmdsl.scoping.AbstractSdmdslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SdmdslScopeProvider extends AbstractSdmdslScopeProvider {
}
