/*
 * generated by Xtext 2.10.0
 */
package org.xtext.alma.container.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.alma.container.container.Container;
import org.xtext.alma.container.container.ContainerField;
import org.xtext.alma.container.container.ContainerPackage;
import org.xtext.alma.container.services.ContainerGrammarAccess;

@SuppressWarnings("all")
public class ContainerSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ContainerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ContainerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ContainerPackage.CONTAINER:
				sequence_Container(context, (Container) semanticObject); 
				return; 
			case ContainerPackage.CONTAINER_FIELD:
				sequence_ContainerField(context, (ContainerField) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ContainerField returns ContainerField
	 *
	 * Constraint:
	 *     (primitiveType=PrimitiveTypes name=ID readOnly?='readOnly'? initValue=STRING? doc=ML_COMMENT?)
	 */
	protected void sequence_ContainerField(ISerializationContext context, ContainerField semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Container returns Container
	 *
	 * Constraint:
	 *     (doc=ML_COMMENT? name=ID data+=ContainerField*)
	 */
	protected void sequence_Container(ISerializationContext context, Container semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
