/*
 * generated by Xtext 2.10.0
 */
package org.xtext.alma.container.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractContainerScopeProvider extends DelegatingScopeProvider {
}
