/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.container.validation;

import org.xtext.alma.container.validation.AbstractContainerValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ContainerValidator extends AbstractContainerValidator {
}
