/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EnumerationStandaloneSetup extends EnumerationStandaloneSetupGenerated {

	def static void doSetup() {
		new EnumerationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
