/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.alma.sdmdsl.parser.antlr.internal.InternalSdmdslParser;
import org.xtext.alma.sdmdsl.services.SdmdslGrammarAccess;

public class SdmdslParser extends AbstractAntlrParser {

	@Inject
	private SdmdslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSdmdslParser createParser(XtextTokenStream stream) {
		return new InternalSdmdslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SdmdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SdmdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
