/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SdmdslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/alma/sdmdsl/parser/antlr/internal/InternalSdmdsl.tokens");
	}
}
