/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.container.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class ContainerQuickfixProvider extends DefaultQuickfixProvider {
}
