/*
 * generated by Xtext 2.10.0
 */
package org.xtext.alma.container.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.alma.container.parser.antlr.internal.InternalContainerParser;
import org.xtext.alma.container.services.ContainerGrammarAccess;

public class ContainerParser extends AbstractAntlrParser {

	@Inject
	private ContainerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalContainerParser createParser(XtextTokenStream stream) {
		return new InternalContainerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Container";
	}

	public ContainerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ContainerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
