/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.alma.enumeration.enumeration.EnumType;
import org.xtext.alma.enumeration.tests.EnumerationInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(EnumerationInjectorProvider.class)
@SuppressWarnings("all")
public class EnumerationParsingTest {
  @Inject
  private ParseHelper<EnumType> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final EnumType result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
