/**
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.container.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.alma.container.container.Container;
import org.xtext.alma.container.tests.ContainerInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(ContainerInjectorProvider.class)
@SuppressWarnings("all")
public class ContainerParsingTest {
  @Inject
  private ParseHelper<Container> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Container result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
