/*
 * generated by Xtext 2.10.0
 */
package org.xtext.alma.container.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.alma.container.ui.internal.ContainerActivator;

public class ContainerUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ContainerActivator.getInstance().getInjector("org.xtext.alma.container.Container");
	}

}
