/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.alma.sdmdsl.ui.internal.SdmdslActivator;

public class SdmdslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SdmdslActivator.getInstance().getInjector("org.xtext.alma.sdmdsl.Sdmdsl");
	}

}
