/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Defined</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Defined#getDataDimValue <em>Data Dim Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getDefined()
 * @model
 * @generated
 */
public interface Defined extends Dimensions
{
  /**
   * Returns the value of the '<em><b>Data Dim Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Dim Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Dim Value</em>' containment reference.
   * @see #setDataDimValue(Addition)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getDefined_DataDimValue()
   * @model containment="true"
   * @generated
   */
  Addition getDataDimValue();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Defined#getDataDimValue <em>Data Dim Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Dim Value</em>' containment reference.
   * @see #getDataDimValue()
   * @generated
   */
  void setDataDimValue(Addition value);

} // Defined
