/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dimensions</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getDimensions()
 * @model
 * @generated
 */
public interface Dimensions extends EObject
{
} // Dimensions
