/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Dimensions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.FieldDimensions#getDimValue <em>Dim Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getFieldDimensions()
 * @model
 * @generated
 */
public interface FieldDimensions extends EObject
{
  /**
   * Returns the value of the '<em><b>Dim Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dim Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dim Value</em>' reference.
   * @see #setDimValue(Field)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getFieldDimensions_DimValue()
   * @model
   * @generated
   */
  Field getDimValue();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.FieldDimensions#getDimValue <em>Dim Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dim Value</em>' reference.
   * @see #getDimValue()
   * @generated
   */
  void setDimValue(Field value);

} // FieldDimensions
