/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.xtext.alma.enumeration.enumeration.EnumType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getPrimitiveType <em>Primitive Type</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getEnumeration <em>Enumeration</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getScalar <em>Scalar</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getDataDim <em>Data Dim</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isAutoIncrementable <em>Auto Incrementable</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToAslice <em>Refs To Aslice</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToOne <em>Refs To One</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToMany <em>Refs To Many</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToManySlices <em>Refs To Many Slices</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getRefersTo <em>Refers To</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getRefersTo2 <em>Refers To2</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getDoc <em>Doc</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField()
 * @model
 * @generated
 */
public interface Field extends EObject
{
  /**
   * Returns the value of the '<em><b>Primitive Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primitive Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primitive Type</em>' attribute.
   * @see #setPrimitiveType(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_PrimitiveType()
   * @model
   * @generated
   */
  String getPrimitiveType();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getPrimitiveType <em>Primitive Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primitive Type</em>' attribute.
   * @see #getPrimitiveType()
   * @generated
   */
  void setPrimitiveType(String value);

  /**
   * Returns the value of the '<em><b>Enumeration</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumeration</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration</em>' reference.
   * @see #setEnumeration(EnumType)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_Enumeration()
   * @model
   * @generated
   */
  EnumType getEnumeration();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getEnumeration <em>Enumeration</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumeration</em>' reference.
   * @see #getEnumeration()
   * @generated
   */
  void setEnumeration(EnumType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Scalar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scalar</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scalar</em>' attribute.
   * @see #setScalar(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_Scalar()
   * @model
   * @generated
   */
  String getScalar();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getScalar <em>Scalar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scalar</em>' attribute.
   * @see #getScalar()
   * @generated
   */
  void setScalar(String value);

  /**
   * Returns the value of the '<em><b>Data Dim</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.alma.sdmdsl.sdmdsl.Dimensions}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data Dim</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Dim</em>' containment reference list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_DataDim()
   * @model containment="true"
   * @generated
   */
  EList<Dimensions> getDataDim();

  /**
   * Returns the value of the '<em><b>Auto Incrementable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Auto Incrementable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Auto Incrementable</em>' attribute.
   * @see #setAutoIncrementable(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_AutoIncrementable()
   * @model
   * @generated
   */
  boolean isAutoIncrementable();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isAutoIncrementable <em>Auto Incrementable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Auto Incrementable</em>' attribute.
   * @see #isAutoIncrementable()
   * @generated
   */
  void setAutoIncrementable(boolean value);

  /**
   * Returns the value of the '<em><b>Refs To Aslice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refs To Aslice</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refs To Aslice</em>' attribute.
   * @see #setRefsToAslice(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_RefsToAslice()
   * @model
   * @generated
   */
  boolean isRefsToAslice();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToAslice <em>Refs To Aslice</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refs To Aslice</em>' attribute.
   * @see #isRefsToAslice()
   * @generated
   */
  void setRefsToAslice(boolean value);

  /**
   * Returns the value of the '<em><b>Refs To One</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refs To One</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refs To One</em>' attribute.
   * @see #setRefsToOne(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_RefsToOne()
   * @model
   * @generated
   */
  boolean isRefsToOne();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToOne <em>Refs To One</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refs To One</em>' attribute.
   * @see #isRefsToOne()
   * @generated
   */
  void setRefsToOne(boolean value);

  /**
   * Returns the value of the '<em><b>Refs To Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refs To Many</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refs To Many</em>' attribute.
   * @see #setRefsToMany(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_RefsToMany()
   * @model
   * @generated
   */
  boolean isRefsToMany();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToMany <em>Refs To Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refs To Many</em>' attribute.
   * @see #isRefsToMany()
   * @generated
   */
  void setRefsToMany(boolean value);

  /**
   * Returns the value of the '<em><b>Refs To Many Slices</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refs To Many Slices</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refs To Many Slices</em>' attribute.
   * @see #setRefsToManySlices(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_RefsToManySlices()
   * @model
   * @generated
   */
  boolean isRefsToManySlices();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#isRefsToManySlices <em>Refs To Many Slices</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refs To Many Slices</em>' attribute.
   * @see #isRefsToManySlices()
   * @generated
   */
  void setRefsToManySlices(boolean value);

  /**
   * Returns the value of the '<em><b>Refers To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refers To</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refers To</em>' attribute.
   * @see #setRefersTo(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_RefersTo()
   * @model
   * @generated
   */
  String getRefersTo();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getRefersTo <em>Refers To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refers To</em>' attribute.
   * @see #getRefersTo()
   * @generated
   */
  void setRefersTo(String value);

  /**
   * Returns the value of the '<em><b>Refers To2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refers To2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refers To2</em>' attribute.
   * @see #setRefersTo2(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_RefersTo2()
   * @model
   * @generated
   */
  String getRefersTo2();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getRefersTo2 <em>Refers To2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refers To2</em>' attribute.
   * @see #getRefersTo2()
   * @generated
   */
  void setRefersTo2(String value);

  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doc</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getField_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Field#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

} // Field
