/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplication</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Multiplication#getMultValue <em>Mult Value</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Multiplication#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getMultiplication()
 * @model
 * @generated
 */
public interface Multiplication extends EObject
{
  /**
   * Returns the value of the '<em><b>Mult Value</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.alma.sdmdsl.sdmdsl.Primary}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mult Value</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mult Value</em>' containment reference list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getMultiplication_MultValue()
   * @model containment="true"
   * @generated
   */
  EList<Primary> getMultValue();

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getMultiplication_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

} // Multiplication
