/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not Defined</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.NotDefined#getObj <em>Obj</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getNotDefined()
 * @model
 * @generated
 */
public interface NotDefined extends Dimensions
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' attribute.
   * @see #setObj(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getNotDefined_Obj()
   * @model
   * @generated
   */
  String getObj();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.NotDefined#getObj <em>Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' attribute.
   * @see #getObj()
   * @generated
   */
  void setObj(String value);

} // NotDefined
