/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Primary#getPrimValue <em>Prim Value</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Primary#getPrimAddValue <em>Prim Add Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends EObject
{
  /**
   * Returns the value of the '<em><b>Prim Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prim Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prim Value</em>' containment reference.
   * @see #setPrimValue(EObject)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getPrimary_PrimValue()
   * @model containment="true"
   * @generated
   */
  EObject getPrimValue();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Primary#getPrimValue <em>Prim Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prim Value</em>' containment reference.
   * @see #getPrimValue()
   * @generated
   */
  void setPrimValue(EObject value);

  /**
   * Returns the value of the '<em><b>Prim Add Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prim Add Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prim Add Value</em>' containment reference.
   * @see #setPrimAddValue(Addition)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getPrimary_PrimAddValue()
   * @model containment="true"
   * @generated
   */
  Addition getPrimAddValue();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Primary#getPrimAddValue <em>Prim Add Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prim Add Value</em>' containment reference.
   * @see #getPrimAddValue()
   * @generated
   */
  void setPrimAddValue(Addition value);

} // Primary
