/**
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.sdmdsl.sdmdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getDoc <em>Doc</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isKeyLevel <em>Key Level</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getKeyData <em>Key Data</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isReqLevel <em>Req Level</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getReqData <em>Req Data</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isOptLevel <em>Opt Level</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getOptData <em>Opt Data</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isGlobalLevel <em>Global Level</em>}</li>
 *   <li>{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getGlobalData <em>Global Data</em>}</li>
 * </ul>
 *
 * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable()
 * @model
 * @generated
 */
public interface Table extends EObject
{
  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doc</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Table#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Key Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Level</em>' attribute.
   * @see #setKeyLevel(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_KeyLevel()
   * @model
   * @generated
   */
  boolean isKeyLevel();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isKeyLevel <em>Key Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key Level</em>' attribute.
   * @see #isKeyLevel()
   * @generated
   */
  void setKeyLevel(boolean value);

  /**
   * Returns the value of the '<em><b>Key Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.alma.sdmdsl.sdmdsl.Field}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Data</em>' containment reference list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_KeyData()
   * @model containment="true"
   * @generated
   */
  EList<Field> getKeyData();

  /**
   * Returns the value of the '<em><b>Req Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Req Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req Level</em>' attribute.
   * @see #setReqLevel(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_ReqLevel()
   * @model
   * @generated
   */
  boolean isReqLevel();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isReqLevel <em>Req Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req Level</em>' attribute.
   * @see #isReqLevel()
   * @generated
   */
  void setReqLevel(boolean value);

  /**
   * Returns the value of the '<em><b>Req Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.alma.sdmdsl.sdmdsl.Field}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Req Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req Data</em>' containment reference list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_ReqData()
   * @model containment="true"
   * @generated
   */
  EList<Field> getReqData();

  /**
   * Returns the value of the '<em><b>Opt Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Opt Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opt Level</em>' attribute.
   * @see #setOptLevel(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_OptLevel()
   * @model
   * @generated
   */
  boolean isOptLevel();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isOptLevel <em>Opt Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opt Level</em>' attribute.
   * @see #isOptLevel()
   * @generated
   */
  void setOptLevel(boolean value);

  /**
   * Returns the value of the '<em><b>Opt Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.alma.sdmdsl.sdmdsl.Field}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Opt Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opt Data</em>' containment reference list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_OptData()
   * @model containment="true"
   * @generated
   */
  EList<Field> getOptData();

  /**
   * Returns the value of the '<em><b>Global Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Level</em>' attribute.
   * @see #setGlobalLevel(boolean)
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_GlobalLevel()
   * @model
   * @generated
   */
  boolean isGlobalLevel();

  /**
   * Sets the value of the '{@link org.xtext.alma.sdmdsl.sdmdsl.Table#isGlobalLevel <em>Global Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global Level</em>' attribute.
   * @see #isGlobalLevel()
   * @generated
   */
  void setGlobalLevel(boolean value);

  /**
   * Returns the value of the '<em><b>Global Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.alma.sdmdsl.sdmdsl.GlobalField}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Global Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global Data</em>' containment reference list.
   * @see org.xtext.alma.sdmdsl.sdmdsl.SdmdslPackage#getTable_GlobalData()
   * @model containment="true"
   * @generated
   */
  EList<GlobalField> getGlobalData();

} // Table
