/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEnumerationScopeProvider extends DelegatingScopeProvider {
}
