/*
 * generated by Xtext 2.9.0
 */
package org.xtext.alma.sdmdsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SdmdslProposalProvider extends AbstractSdmdslProposalProvider {
}
