/*
 * generated by Xtext 2.9.1
 */
package org.xtext.alma.enumeration.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.alma.enumeration.enumeration.EnumType

@RunWith(XtextRunner)
@InjectWith(EnumerationInjectorProvider)
class EnumerationParsingTest{

	@Inject
	ParseHelper<EnumType> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
